#include <stdio.h>

int main()
{
    FILE *fp;

    // fp = fopen("实验2-4-1 统计各位数字之和是5的数.c", "w");
    // fclose(fp);
    // fp = fopen("实验2-4-5 简单实现x的n次方.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-1 使用函数计算两个复数之积.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-2 符号函数.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-3 使用函数求奇数和.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-4 使用函数计算两点间的距离.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-5 使用函数求素数和.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-6 使用函数判断完全平方数.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-7 使用函数求1到10的阶乘和.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-8 使用函数统计指定数字的个数.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-9 使用函数输出水仙花数.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-10 使用函数求余弦函数的近似值.c", "w");
    // fclose(fp);
    // fp = fopen("实验5-11 使用函数求最大公约数.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-2 分类统计字符个数.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-3 使用函数求特殊a串数列和.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-4 使用函数输出指定范围内的完数.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-5 使用函数输出指定范围内的Fibonacci数.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-6 使用函数验证哥德巴赫猜想.c", "w");
    // fclose(fp);
    // fp = fopen("实验6-7 使用函数输出一个整数的逆序数.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-1 利用指针找最大值.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-2 计算两数的和与差.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-3 拆分实数的整数与小数部分.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-4 使用函数的选择法排序.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-5 在数组中查找指定元素.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-6 函数实现字符串逆序.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-7 数组循环右移.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-1-8 报数.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-3 删除字符.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-4 使用函数实现字符串部分复制.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-5 判断回文字符串.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-6 分类统计各类字符个数.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-7 字符串的连接.c", "w");
    // fclose(fp);
    // fp = fopen("实验8-2-9 长整数转化成16进制字符串.c", "w");
    // fclose(fp);
    // fp = fopen("实验9-4 计算两个复数之积.c", "w");
    // fclose(fp);
    // fp = fopen("实验9-6 按等级统计学生成绩.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-2 判断满足条件的三位数.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-3 递归求阶乘和.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-4 递归实现指数函数.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-5 递归求简单交错幂级数的部分和.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-6 递归计算Ackermenn函数.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-7 递归求Fabonacci数列.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-8 递归计算P函数.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-9 十进制转换二进制.c", "w");
    // fclose(fp);
    // fp = fopen("实验10-10 递归实现顺序输出整数.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-1-2 输出月份英文名.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-1-3 查找星期.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-1-4 计算最长的字符串长度.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-1-6 指定位置输出字符串.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-1-8 查找子串.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-1 建立学生信息链表.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-2 学生成绩链表处理.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-3 逆序数据建立链表.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-4 删除单链表偶数节点.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-5 链表拼接.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-6 奇数值结点链表.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-7 统计专业人数.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-8 单链表结点删除.c", "w");
    // fclose(fp);
    // fp = fopen("实验11-2-9 链表逆置.c", "w");
    // fclose(fp);
    fp = fopen("实验1-1	Hello World.c!", "w");
    fclose(fp);
    fp = fopen("实验1-2	Welcome to You.c!", "w");
    fclose(fp);
    fp = fopen("实验1-3	Programming in C is fun.c!", "w");
    fclose(fp);
    fp = fopen("实验1-4	输出三角形.c", "w");
    fclose(fp);
    fp = fopen("实验1-5	输出菱形图案.c", "w");
    fclose(fp);
    fp = fopen("实验1-6	输出带框文字.c", "w");
    fclose(fp);
    fp = fopen("实验1-7	What is a computer.c?", "w");
    fclose(fp);
    fp = fopen("实验1-8	输出倒三角图案.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-1 计算摄氏温度.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-2 温度转换.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-3 计算物体自由下落的距离.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-4 计算平均分.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-5 将x的平方赋值给y.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-6 计算华氏温度.c", "w");
    fclose(fp);
    fp = fopen("实验2-1-7 整数152的各位数字.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-1 计算分段函数.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-2 计算摄氏温度.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-3 计算存款利息.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-4 计算分段函数.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-5 求整数均值.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-6 计算分段函数[3.c]", "w");
    fclose(fp);
    fp = fopen("实验2-2-7 整数四则运算.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-8 阶梯电价.c", "w");
    fclose(fp);
    fp = fopen("实验2-2-9 计算火车运行时间.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-1 求1到100的和.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-2 求N分之一序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-3 求奇数分之一序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-4 求简单交错序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-5 输出华氏-摄氏温度转换表.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-6 求交错序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-3-7 求平方与倒数序列的部分和.c", "w");
    fclose(fp);
    fp = fopen("实验2-4-2 生成3的乘方表.c", "w");
    fclose(fp);
    fp = fopen("实验2-4-3 求平方根序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-4-4 求阶乘序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验2-4-6 求幂之和.c", "w");
    fclose(fp);
    fp = fopen("实验2-4-7 求组合数.c", "w");
    fclose(fp);
    fp = fopen("实验3-1 求一元二次方程的根.c", "w");
    fclose(fp);
    fp = fopen("实验3-2 计算符号函数的值.c", "w");
    fclose(fp);
    fp = fopen("实验3-3 比较大小.c", "w");
    fclose(fp);
    fp = fopen("实验3-4 统计字符.c", "w");
    fclose(fp);
    fp = fopen("实验3-5 查询水果价格.c", "w");
    fclose(fp);
    fp = fopen("实验3-6 计算个人所得税.c", "w");
    fclose(fp);
    fp = fopen("实验3-7 统计学生成绩.c", "w");
    fclose(fp);
    fp = fopen("实验3-8 输出三角形面积和周长.c", "w");
    fclose(fp);
    fp = fopen("实验3-9 三天打鱼两天晒网.c", "w");
    fclose(fp);
    fp = fopen("实验3-10 高速公路超速处罚.c", "w");
    fclose(fp);
    fp = fopen("实验3-11 计算油费.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-1 最大公约数和最小公倍数.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-2 求奇数和.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-3 找出最小值.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-4 求整数的位数及各位数字之和.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-5 韩信点兵.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-6 求分数序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-7 特殊a串数列求和.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-8 求给定精度的简单交错序列部分和.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-9 猜数字游戏.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-10 兔子繁衍问题.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-11 高空坠球.c", "w");
    fclose(fp);
    fp = fopen("实验4-1-12 黑洞数.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-2 求e的近似值.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-3 验证“哥德巴赫猜想”.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-4 换硬币.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-5 水仙花数.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-6 输出三角形字符阵列.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-7 找完数.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-8 输出整数各位数字.c", "w");
    fclose(fp);
    fp = fopen("实验4-2-9 梅森数.c", "w");
    fclose(fp);
    fp = fopen("实验6-1 近似求PI.c", "w");
    fclose(fp);
    fp = fopen("实验6-8 简单计算器.c", "w");
    fclose(fp);
    fp = fopen("实验6-9 统计一行文本的单词个数.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-1 简化的插入排序.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-2 求最大值及其下标.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-3 将数组中的数逆序存放.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-4 找出不是两个数组共有的元素.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-5 选择法排序.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-6 求一批整数中出现最多的个位数字.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-7 查找整数.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-8 输出数组元素.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-9 数字加密.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-10 交换最小值和最大值.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-11 求整数序列中出现次数最多的数.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-12 组个最小数.c", "w");
    fclose(fp);
    fp = fopen("实验7-1-13 装箱问题.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-1 求矩阵各行元素之和.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-2 矩阵运算.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-3 求矩阵的局部极大值.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-4 计算天数.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-5 判断上三角矩阵.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-6 打印杨辉三角.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-7 方阵循环右移.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-8 找鞍点.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-9 螺旋方阵.c", "w");
    fclose(fp);
    fp = fopen("实验7-2-10 简易连连看.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-1 字符串逆序.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-2 查找指定字符.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-3 统计大写辅音字母.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-4 字符串替换.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-5 输出大写英文字母.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-6 字符串转换成十进制整数.c", "w");
    fclose(fp);
    fp = fopen("实验7-3-7 字符转换.c", "w");
    fclose(fp);
    return 0;
}
